# Generated by Django 2.2.4 on 2019-08-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=4000)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
