# Generated by Django 2.2.4 on 2019-08-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='body_text_1',
            field=models.CharField(blank=True, max_length=10000, verbose_name='Descrizione'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body_text_2',
            field=models.TextField(blank=True, max_length=10000, verbose_name='Testo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body_text',
            field=models.TextField(max_length=10000, verbose_name='Testo'),
        ),
    ]
