# Generated by Django 2.2.4 on 2019-08-22 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190816_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('image', models.ImageField(null=True, upload_to='', verbose_name='Foto')),
                ('description', models.TextField(max_length=1000, verbose_name='Bio')),
            ],
        ),
    ]
