# Generated by Django 2.2.4 on 2019-08-22 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_instructor'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Articolo', 'verbose_name_plural': 'Articoli'},
        ),
        migrations.AlterModelOptions(
            name='frontpage',
            options={'verbose_name': 'Pagina principale', 'verbose_name_plural': 'Pagina principale'},
        ),
        migrations.AlterModelOptions(
            name='frontpic',
            options={'verbose_name': 'Foto slideshow', 'verbose_name_plural': 'Foto slideshow'},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name': 'Istruttore', 'verbose_name_plural': 'Istruttori'},
        ),
    ]
