# Generated by Django 2.2.4 on 2019-08-28 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20190827_1051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Istruttori',
        ),
    ]
